import { readFileSync, writeFileSync, existsSync, realpathSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

function replaceOnce(source, from, to) {
  if (source.split(from).length !== 2) throw new Error(`Pinned Jev source no longer matches integration anchor: ${from}`);
  return source.replace(from, to);
}

const HEADER = '// Generated by laya-jev prepare.mjs from the pinned upstream source.\n';
const digest = (source) => createHash('sha256').update(source).digest('hex');

function writeGenerated(file, source, previous = []) {
  const content = `${HEADER}// Content-SHA256: ${digest(source)}\n${source}`;
  if (existsSync(file)) {
    const current = readFileSync(file, 'utf8');
    if (current === content) return;
    const match = current.startsWith(HEADER) && /^\/\/ Content-SHA256: ([a-f0-9]{64})\n([\s\S]*)$/.exec(current.slice(HEADER.length));
    const intact = match && digest(match[2]) === match[1];
    if (!intact && !previous.includes(current)) throw new Error(`Preserving differing file ${file}; choose a fresh INSTALL_DIR.`);
  }
  writeFileSync(file, content, { mode: 0o600 });
}

// Generate clearly named integration copies; upstream tracked source stays pristine.
// These changes concern generation transport and OpenCode turn detection, not Laya's API.
export function prepare(jevRoot) {
  const readSource = (name) => readFileSync(join(jevRoot, 'src', `${name}.mjs`), 'utf8').replaceAll('\r\n', '\n');
  const log = readSource('log').replace('".jev-claude.log"', '".laya-router.log"').replace('[jev]', '[laya-router]')
    .replace('appendFileSync(LOG_FILE, `${new Date().toISOString()} ${text}`);', 'appendFileSync(LOG_FILE, `${new Date().toISOString()} ${text}`, { mode: 0o600 });');
  writeGenerated(join(jevRoot, 'src/log-local.mjs'), log);
  let router = replaceOnce(readSource('router'), '"./log.mjs"', '"./log-local.mjs"');
  router = replaceOnce(router, 'timeout: THRESHOLDS.jevTimeoutMs,', 'timeout: THRESHOLDS.jevTimeoutMs,\n    fetch: (input, init) => fetch(input, { ...init, redirect: "error" }),');
  router = replaceOnce(router, '${err.message}', 'local classifier request failed');
  writeGenerated(join(jevRoot, 'src/router-local.mjs'), router);
  let settings = readSource('settings');
  settings = replaceOnce(settings, 'return model === AUTO_MODEL ? undefined : model;', 'return model === AUTO_MODEL || model === "laya-router" ? undefined : model;');
  settings = replaceOnce(settings, 'if (settings.model !== AUTO_MODEL) return false;', 'if (settings.model !== AUTO_MODEL && settings.model !== "laya-router") return false;');
  settings = replaceOnce(settings, 'join(homedir(), ".claude", "settings.json")', 'join(process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude"), "settings.json")');
  writeGenerated(join(jevRoot, 'src/settings-local.mjs'), settings);
  writeGenerated(join(jevRoot, 'src/status-local.mjs'), `import { writeDecision as write, writeStatus } from "./status.mjs";
export { writeStatus };
export function writeDecision(session, decision) {
  const { tier, model, confidence, metrics, reason, at } = decision;
  return write(session, { tier, model, confidence, metrics, reason, at });
}
`);
  for (const name of ['proxy', 'codex-proxy']) {
    let source = readSource(name);
    source = replaceOnce(source, 'const server = http.createServer((req, res) => {', `const server = http.createServer((req, res) => {
    const cancelled = new AbortController();
    res.once("close", () => cancelled.abort());
    req.once("aborted", () => cancelled.abort());
    req.on("error", () => cancelled.abort());`);
    if (name === 'codex-proxy') {
      source = replaceOnce(source, 'const cancelled = new AbortController();', 'if (req.method === "HEAD") return res.writeHead(200).end();\n    const cancelled = new AbortController();');
    }
    const chunk = name === 'proxy' ? 'c' : 'chunk';
    source = replaceOnce(source, `req.on("data", (${chunk}) => chunks.push(${chunk}));`, `let bytes = 0;
    req.on("data", (chunk) => {
      bytes += chunk.length;
      if (bytes > 8 * 1024 * 1024) {
        if (!res.headersSent) res.writeHead(413, { "connection": "close" }).end();
        cancelled.abort();
        req.pause();
        return;
      }
      chunks.push(chunk);
    });`);
    source = replaceOnce(source, 'let out = Buffer.concat(chunks);', 'if (cancelled.signal.aborted) return;\n      let out = Buffer.concat(chunks);');
    const routeEnd = name === 'proxy'
      ? 'const jev = await route({ prompt, current: currentModel, contextTokens, models });'
      : 'const jev = await route({ prompt, current: currentModel, contextTokens, models: candidates });';
    source = replaceOnce(source, routeEnd, `${routeEnd}\n              if (cancelled.signal.aborted) return;`);
    source = replaceOnce(source, 'const transport = target.protocol', 'if (cancelled.signal.aborted) return;\n      const transport = target.protocol');
    source = replaceOnce(source, 'hostname: target.hostname,', 'signal: cancelled.signal,\n          hostname: target.hostname,');
    source = replaceOnce(source, 'if (!res.headersSent) res.writeHead(502,', 'if (cancelled.signal.aborted || res.destroyed) return;\n        if (!res.headersSent) res.writeHead(502,');
    if (name === 'proxy') {
      source = replaceOnce(source, 'export function newTurnPrompt(body) {', 'export function newTurnPrompt(body, requireTools = true) {');
      source = replaceOnce(source, 'if (!Array.isArray(body?.tools) || body.tools.length === 0) return null;', 'if (requireTools && (!Array.isArray(body?.tools) || body.tools.length === 0)) return null;');
      source = replaceOnce(source, 'route = askJev } = {})', 'route = askJev, newTurn = newTurnPrompt } = {})');
      source = replaceOnce(source, 'const prompt = newTurnPrompt(body);', 'const prompt = newTurn(body);');
    }
    // Recognize the exact previous generated version so existing installs can upgrade.
    const previous = HEADER + source;
    source = replaceOnce(source, '"./router.mjs"', '"./router-local.mjs"');
    source = replaceOnce(source, '"./log.mjs"', '"./log-local.mjs"');
    source = replaceOnce(source, '"./status.mjs"', '"./status-local.mjs"');
    source = `import { observeUsage } from ${JSON.stringify(new URL('./usage.mjs', import.meta.url).href)};\n` + source;
    source = replaceOnce(source, 'let out = Buffer.concat(chunks);', `let usageSession = process.env.LAYA_USAGE_SESSION_ID || ${JSON.stringify(name === 'proxy' ? 'claude' : 'codex')};\n      let usageModel;\n      let out = Buffer.concat(chunks);`);
    source = replaceOnce(source, 'const body = JSON.parse(out.toString());', 'const body = JSON.parse(out.toString());\n          ' + (name === 'proxy'
      ? 'usageSession = sessionOf(body) || usageSession;'
      : 'usageSession = req.headers["session_id"] || req.headers["x-session-id"] || body.prompt_cache_key || usageSession;'));
    source = replaceOnce(source, 'out = Buffer.from(JSON.stringify(body));', 'usageModel = body.model;\n          out = Buffer.from(JSON.stringify(body));');
    source = replaceOnce(source, 'const headers = { ...req.headers, host: target.host };', 'const headers = { ...req.headers, host: target.host };\n      delete headers["accept-encoding"];');
    if (name === 'proxy') {
      source = replaceOnce(source, '  isAuto,', '  isAuto as upstreamIsAuto,');
      source = 'const isAuto = (model) => model === "laya-router" || upstreamIsAuto(model);\n' + source;
      source = replaceOnce(source, '(up) => {', `(up) => {
          up.on("error", () => res.destroy());
          up.on("aborted", () => res.destroy());
          up.on("close", () => { if (!up.complete) res.destroy(); });
          void observeUsage(up, { client: "claude", sessionID: usageSession, model: usageModel });`);
    } else {
      source = replaceOnce(source, 'export const CODEX_AUTO_MODEL = "jev-router";', 'export const CODEX_AUTO_MODEL = "laya-router";');
      source = replaceOnce(source, 'body.model === CODEX_AUTO_MODEL', '(body.model === CODEX_AUTO_MODEL || body.model === "jev-router")');
      source = source.replaceAll('"Jev Router"', '"laya-router"').replaceAll('[Jev]', '[laya-router]')
        .replace('Jev picks the cheapest model', 'Laya picks the cheapest model')
        .replace('Add JEV_API_KEY=... to ~/.jev-router.env and restart jev-codex.', 'Check the local Laya server and restart laya-codex.');
      source = replaceOnce(source, '(response) => {', `(response) => {
          response.on("error", () => res.destroy());
          response.on("aborted", () => res.destroy());
          response.on("close", () => { if (!response.complete) res.destroy(); });
          void observeUsage(response, { client: "codex", sessionID: usageSession, model: usageModel });`);
    }
    writeGenerated(join(jevRoot, 'src', `${name}-local.mjs`), source, [previous]);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href) {
  if (!process.argv[2]) throw new Error('Pass the absolute Jev checkout path');
  prepare(process.argv[2]);
}
