import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { prepare } from './prepare.mjs';

test('generated copies upgrade intact versions, preserve edits, and leave pinned sources unchanged', {
  skip: !process.env.JEV_ROOT && 'Set JEV_ROOT to the pinned checkout',
}, async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'laya-prepare-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, 'src'));
  const sources = new Map();
  for (const name of ['proxy', 'codex-proxy', 'router', 'log', 'settings']) {
    const source = await readFile(join(process.env.JEV_ROOT, 'src', `${name}.mjs`), 'utf8');
    sources.set(name, source);
    await writeFile(join(root, 'src', `${name}.mjs`), source);
  }
  prepare(root);
  const generated = await readFile(join(root, 'src/proxy-local.mjs'), 'utf8');
  assert.match(generated, /model === "laya-router"/);
  assert.match(generated, /observeUsage\(up/);
  assert.match(await readFile(join(root, 'src/log-local.mjs'), 'utf8'), /\[laya-router\]/);
  prepare(root);
  assert.equal(await readFile(join(root, 'src/proxy-local.mjs'), 'utf8'), generated);

  const olderSource = 'export const olderIntegration = true;\n';
  const hash = createHash('sha256').update(olderSource).digest('hex');
  await writeFile(join(root, 'src/proxy-local.mjs'), `// Generated by laya-jev prepare.mjs from the pinned upstream source.\n// Content-SHA256: ${hash}\n${olderSource}`);
  prepare(root);
  assert.equal(await readFile(join(root, 'src/proxy-local.mjs'), 'utf8'), generated);

  const edited = generated + '// User customization\n';
  await writeFile(join(root, 'src/proxy-local.mjs'), edited);
  assert.throws(() => prepare(root), /Preserving differing file/);
  assert.equal(await readFile(join(root, 'src/proxy-local.mjs'), 'utf8'), edited);
  for (const [name, source] of sources) {
    assert.equal(await readFile(join(root, 'src', `${name}.mjs`), 'utf8'), source);
  }
});
